language: java
jdk:
  - oraclejdk11

jobs:
  include:
    - stage: Compile
      script: mvn clean compile -DskipITTests=true -Dskip.unit.tests=true
    - stage: Unit Tests
      script: mvn clean package -DskipITTests=true -Dskip.unit.tests=false
    - stage: Integration Tests
      script: mvn clean verify -DskipITTests=false -Dskip.unit.tests=true
    - stage: Package
      script: mvn clean package -DskipITTests=true -Dskip.unit.tests=true