language: java
jdk:
  - oraclejdk11

jobs:
  include:
    - stage: Compile
      script: mvn clean compile -Dskip.unit.tests=true
    - stage: Unit Tests
      script: mvn clean package -Dskip.unit.tests=false
    - stage: Integration Tests
      script: mvn clean integration-test
    - stage: Package
      script: mvn clean package -Dskip.unit.tests=true