version: '3.6'

services:

  activemq:
    networks:
      - access-log-monitor-service-net
    image: 'rmohr/activemq'
    ports:
      - '8161:8161'
      - '61616:61616'

networks:
  access-log-monitor-service-net: