version: '3.6'

services:

  mariadb:
    networks:
      - access-log-monitor-service-net
    image: 'mariadb'
    ports:
      - '3308:3306'
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      TZ: 'Europe/Paris'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'httpmonitor'

  activemq:
    networks:
      - access-log-monitor-service-net
    image: 'rmohr/activemq'
    ports:
      - '8161:8161'
      - '61616:61616'

networks:
  access-log-monitor-service-net: